//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSGatewayService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOutgoingSMS
    {
        public int OutID { get; set; }
        public string OutPhoneNumber { get; set; }
        public string OutgoingMessage { get; set; }
        public string OutDate { get; set; }
        public string OutMessageType { get; set; }
        public string OutTime { get; set; }
        public Nullable<bool> OutProcessed { get; set; }
        public string AccountNo { get; set; }
        public string STAN { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public int Trials { get; set; }
        public string SubmitResponse { get; set; }
        public string Provider { get; set; }
    }
}
